### ISSUE TITLE
Major bug with code

### ISSUE THREAD

**Issue by zaini** [ayanahmad571/roomba_plan_maker#1]
I see you've used PHP. You might wanna fix that.

**Comment by MohammadABH** [comment]
Agreed, big issue. Could you look into it any time soon?

**Comment by ayanahmad571** [comment]
Good catch, I actually thought about coding it in JS.
But realized I'd spend more time debugging code than I spent writing it.

**Comment by zaini** [comment]
I see. Well I'll close the issue seeing as it seems like you're a lost cause. Good day!
